<?php

namespace WM\FilmBundle\Repository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends \Doctrine\ORM\EntityRepository
{
}
